[opener]
viewJson = [{ run = 'jless "$@"', desc = "Open" }]
[open]
rules = [
  # { mime = "application/json", use = "edit" },
  { name = "*.json", use = "viewJson" },

]
[plugin]
prepend_previewers = [{ name = "*.md", run = "glow" }]

[manager]
show_hidden = true
